### ISSUE TITLE
Сверстать футер

### ISSUE THREAD

**Issue by isqua** [KasiMaru/Nerds#2]
Делать после #1

---

1. Подумай, что входит в футер, а что нет. Возможно, футер состоит из нескольких блоков — это окей, давай верстать их все. Возможно, он состоит из одного блока с кучей элементов — это тоже окей. Если не уверен, можно обсудить заранее. Можешь себе прямоугольничками разлиновать макет. Не забудь про точки силы.
2. Создай ветку `issues/2`.
3. Сверстай в ней футер со всеми внутренними блоками/элементами. Но каждый блок должен быть в отдельном файле в папочке `css/blocks`. Типа: `css/blocks/footer.css`, `css/blocks/ololo.css` и т.п. Эти файлы надо подключить в `css/style.css` с помощью импортов.
4. Коммитить ты можешь конечно в любой момент, главное потом запушь это: `git push -u origin issues/2`.
5. [Открой пулл-реквест](https://isqua.ru/blog/2017/04/12/kak-otkryt-pull-riekviest-v-github-i-nie-oblazhatsia/) из `issues/2` в `master`.
6. После код-ревью я «утвержу» пулл-реквест, и ты его вольёшь.

**Comment by KasiMaru** [comment]
Ага, так с фиксом не работает, учтем
